apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zd31ef14g-go 
  janus-idp.io/tekton: zd31ef14g-go
  backstage.io/kubernetes-id: zd31ef14g-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zd31ef14g-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml