apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zd31ef14g-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zd31ef14g-go 
  name: zd31ef14g-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zd31ef14g-go 
